# Generated by Django 4.1.7 on 2023-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topics',
            field=models.CharField(choices=[('SP', 'Спорт'), ('ED', 'Образование'), ('PO', 'Политика'), ('EC', 'Экономика')], default='EC', max_length=2, unique=True),
        ),
    ]
